theme ="nordic"

[editor]
line-number = "relative"
cursorline  =false 
continue-comments =false
completion-timeout = 5
completion-trigger-len=1
bufferline = "multiple"
popup-border = "all"
end-of-line-diagnostics = "hint"


[editor.statusline]
left = ["mode", "spinner","version-control","register"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.file-picker]
hidden =false

[editor.lsp]
display-progress-messages = true
display-inlay-hints =true 


#[editor.whitespace]
#render = "all"

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)


[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable =true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line ="warning"


[keys.normal.space.l]
g =":sh zellij run -n Lazygit -c -f -x 10%% -y 10%% --width 80%% --height 80%%  -- lazygit" 
[keys.normal.space]
e = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/scripts/yazi-picker.sh open %{buffer_name}"

[keys.normal.space.H]
i = ":sh zellij run --name 'Git Inline' --floating --close-on-exit -- bash -c 'git diff HEAD -- %{buffer_name} | delta --features arctic-fox'"

d = ":sh zellij run --name 'Git Side-By-Side'  --close-on-exit -- bash -c 'git diff HEAD -- %{buffer_name} | delta --side-by-side arctic-fox'"

r = ":reset-diff-change"

[keys.normal]
C-r = [
    ":write-all",
    ":insert-output scooter --no-stdin >/dev/tty",
    ":redraw",
    ":reload-all"
]
